In [2]:
import pandas as pd
import numpy

# Sentiment analysis

- Preprocessing
    - remove URLs
    - remove Stopwords
    - Lemmatization
- Sentiment Analysis with nltk

# Crawling Tweets with Hashtag '?'

In [3]:
#pip install tweepy

In [4]:
import os
import tweepy as tw

In [5]:
consumer_key= 'vvoCCekgIRltBaA28KPeqV5PH'
consumer_secret= 'wbJdfJgPQo6bojNVWtX2FoH8RNXMG7OA7xNis1HOS5tt4E3kN7'
access_token= '216684460-uXpFa0MbWSjZyKrLLajc42VELc7GzFZPIs53PV3g'
access_token_secret= 'quTUm4pTmVv9Uy2AZanWQcErohcDdoFWzUWg17pLtTriC'

auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)

In [6]:
# Define the search term and the date_since date as variables
search_words = "bitcoin"
date_since = "2021-11-11"

In [24]:
tweets = tw.Cursor(api.search_tweets, 
                           q=search_words,
                           lang="en",
                           since=date_since).items(2000)

users_tweets = [[tweet.id, tweet.user.screen_name, tweet.text, tweet.created_at, tweet.user.location] for tweet in tweets]

Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Rate limit reached. Sleeping for: 390
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since

In [25]:
#Open dataframe to use Sentiment Analysis
tweet_text = pd.DataFrame(data=users_tweets, 
                    columns=['id', 'user', "text", "created_at", "location"])
tweet_text

,id,user,text,created_at,location
0,1467832717756678145,pooynack,RT @elizajayla: $1900 in #Bitcoin to a random ...,2021-12-06 12:26:05+00:00,
1,1467832717165449218,Stephworley420,RT @dogeofficialceo: Has someone tried turning...,2021-12-06 12:26:05+00:00,Adjacent to the parallel
2,1467832716762783747,haag_don,That how it looks like #Bitcoin https://t.co/n...,2021-12-06 12:26:05+00:00,
3,1467832716456456193,jakewong1977,RT @rektcapital: #BTC Weekly Closes above the ...,2021-12-06 12:26:05+00:00,"North-East Region, Singapore"
4,1467832715307331590,CryptoNews_21,üö®üö® CRYPTO NEWS ALERT! üö®üö®\n\nBitcoin whales mov...,2021-12-06 12:26:04+00:00,"England, United Kingdom"
...,...,...,...,...,...
1995,1467830433954074631,OXBCfoundation,RT @CityAM_Crypto: Crypto AM Daily in associat...,2021-12-06 12:17:01+00:00,"London, England"
1996,1467830432972615691,mrcryptonew,@BitMartExchange @wifedoge ready to take off üí∏...,2021-12-06 12:17:00+00:00,
1997,1467830432716656643,zubairh20518181,RT @AirdropStario: üíß X3 Swap Airdrop üíß\n\nüèÜ Ta...,2021-12-06 12:17:00+00:00,
1998,1467830431953289217,Ramitzez1,RT @TiernahrungPhil: We all know that Bitcoin ...,2021-12-06 12:17:00+00:00,Malaysia
1999,1467830429105688576,ngqucmnh6,RT @AirdropStario: üíß Floki Solana Airdrop üíß\n\...,2021-12-06 12:16:59+00:00,

---

In [9]:
#pip install nltk

In [36]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.sentiment import SentimentIntensityAnalyzer

# NLP
## Preprocessing

In [37]:
dataset = tweet_text

In [38]:
#nltk.download('stopwords')
#nltk.download('wordnet')
#nltk.download('vader_lexicon')

Set lowercase, remove punctuation, remove url:
- "no","nor","not" removed from stopwords because they may be relevant for sentiment

In [39]:
def clean_dataset(dataset):
    for i in range(0, len(dataset)):
        #Tokenize and set words to lowercase 
        review = dataset["text"][i]
        review = ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",review).split())
        review = re.sub("[^a-zA-Z]", " ", review)
        review = review.lower()
        review = review.split()

        #stopwords: 
        all_stopwords = [word for word in stopwords.words("english") if word not in ["no","nor","not"]]
        all_stopwords.extend(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","&amp","amp","amp;","&amp;","nhs"])
        #lemmatization:
        lemma = nltk.wordnet.WordNetLemmatizer()
        review = " ".join([lemma.lemmatize(word) for word in review if word not in set(all_stopwords)])    
        dataset["text"][i] = review

In [40]:
dataset

,id,user,text,created_at,location
0,1467832717756678145,pooynack,RT @elizajayla: $1900 in #Bitcoin to a random ...,2021-12-06 12:26:05+00:00,
1,1467832717165449218,Stephworley420,RT @dogeofficialceo: Has someone tried turning...,2021-12-06 12:26:05+00:00,Adjacent to the parallel
2,1467832716762783747,haag_don,That how it looks like #Bitcoin https://t.co/n...,2021-12-06 12:26:05+00:00,
3,1467832716456456193,jakewong1977,RT @rektcapital: #BTC Weekly Closes above the ...,2021-12-06 12:26:05+00:00,"North-East Region, Singapore"
4,1467832715307331590,CryptoNews_21,üö®üö® CRYPTO NEWS ALERT! üö®üö®\n\nBitcoin whales mov...,2021-12-06 12:26:04+00:00,"England, United Kingdom"
...,...,...,...,...,...
1995,1467830433954074631,OXBCfoundation,RT @CityAM_Crypto: Crypto AM Daily in associat...,2021-12-06 12:17:01+00:00,"London, England"
1996,1467830432972615691,mrcryptonew,@BitMartExchange @wifedoge ready to take off üí∏...,2021-12-06 12:17:00+00:00,
1997,1467830432716656643,zubairh20518181,RT @AirdropStario: üíß X3 Swap Airdrop üíß\n\nüèÜ Ta...,2021-12-06 12:17:00+00:00,
1998,1467830431953289217,Ramitzez1,RT @TiernahrungPhil: We all know that Bitcoin ...,2021-12-06 12:17:00+00:00,Malaysia
1999,1467830429105688576,ngqucmnh6,RT @AirdropStario: üíß Floki Solana Airdrop üíß\n\...,2021-12-06 12:16:59+00:00,

## Sentiment Analysis with nltk

In [41]:
tweet_text["sentiment"] = dict
tweet_text["sentiment_compound"] = 0.0

Determine sentiment via NLTK.Sentiment:
- Values range from [-1, 1]
- -1 is negative, 0 is neutral, 1 is positive

In [42]:
def sentiment_score(dataset):
    sia = SentimentIntensityAnalyzer()
    for i in range(len(dataset)):
        dataset["sentiment"][i] = sia.polarity_scores(dataset["text"][i])
        dataset["sentiment_compound"][i] = dataset["sentiment"][i]["compound"]

In [43]:
sentiment_score(tweet_text)

c:\users\lukas\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
c:\users\lukas\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [44]:
tweet_text

,id,user,text,created_at,location,sentiment,sentiment_compound
0,1467832717756678145,pooynack,RT @elizajayla: $1900 in #Bitcoin to a random ...,2021-12-06 12:26:05+00:00,,"{'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'comp...",0.3612
1,1467832717165449218,Stephworley420,RT @dogeofficialceo: Has someone tried turning...,2021-12-06 12:26:05+00:00,Adjacent to the parallel,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
2,1467832716762783747,haag_don,That how it looks like #Bitcoin https://t.co/n...,2021-12-06 12:26:05+00:00,,"{'neg': 0.0, 'neu': 0.706, 'pos': 0.294, 'comp...",0.3612
3,1467832716456456193,jakewong1977,RT @rektcapital: #BTC Weekly Closes above the ...,2021-12-06 12:26:05+00:00,"North-East Region, Singapore","{'neg': 0.0, 'neu': 0.902, 'pos': 0.098, 'comp...",0.3612
4,1467832715307331590,CryptoNews_21,üö®üö® CRYPTO NEWS ALERT! üö®üö®\n\nBitcoin whales mov...,2021-12-06 12:26:04+00:00,"England, United Kingdom","{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.6731
...,...,...,...,...,...,...,...
1995,1467830433954074631,OXBCfoundation,RT @CityAM_Crypto: Crypto AM Daily in associat...,2021-12-06 12:17:01+00:00,"London, England","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
1996,1467830432972615691,mrcryptonew,@BitMartExchange @wifedoge ready to take off üí∏...,2021-12-06 12:17:00+00:00,,"{'neg': 0.0, 'neu': 0.8, 'pos': 0.2, 'compound...",0.3612
1997,1467830432716656643,zubairh20518181,RT @AirdropStario: üíß X3 Swap Airdrop üíß\n\nüèÜ Ta...,2021-12-06 12:17:00+00:00,,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
1998,1467830431953289217,Ramitzez1,RT @TiernahrungPhil: We all know that Bitcoin ...,2021-12-06 12:17:00+00:00,Malaysia,"{'neg': 0.0, 'neu': 0.891, 'pos': 0.109, 'comp...",0.4003
1999,1467830429105688576,ngqucmnh6,RT @AirdropStario: üíß Floki Solana Airdrop üíß\n\...,2021-12-06 12:16:59+00:00,,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000

In [45]:
tweet_ids = tweet_text[['id', 'sentiment', 'sentiment_compound']]

In [46]:
tweet_ids

,id,sentiment,sentiment_compound
0,1467832717756678145,"{'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'comp...",0.3612
1,1467832717165449218,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
2,1467832716762783747,"{'neg': 0.0, 'neu': 0.706, 'pos': 0.294, 'comp...",0.3612
3,1467832716456456193,"{'neg': 0.0, 'neu': 0.902, 'pos': 0.098, 'comp...",0.3612
4,1467832715307331590,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.6731
...,...,...,...
1995,1467830433954074631,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
1996,1467830432972615691,"{'neg': 0.0, 'neu': 0.8, 'pos': 0.2, 'compound...",0.3612
1997,1467830432716656643,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
1998,1467830431953289217,"{'neg': 0.0, 'neu': 0.891, 'pos': 0.109, 'comp...",0.4003
1999,1467830429105688576,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000

Sort dataset by sentiment and create a sub-dataset with location only:

In [47]:
tweet_ids = tweet_text.sort_values("sentiment_compound", ascending=False, ignore_index=True)

---

Export:

In [49]:
tweet_ids.to_csv("../sentiment/saved_tweet_ids/tweet_ids.csv")
tweet_text.to_csv("../sentiment/saved_sentiment_data/tweet_complete.csv")